name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Clean install dependencies
      run: |
        npm install --no-package-lock
        npm install autoprefixer@9.8.8 postcss@7.0.39 tailwindcss@3.3.0 react-icons --save-exact
        
    - name: Setup PostCSS config
      run: |
        echo "module.exports = { plugins: ['tailwindcss', 'autoprefixer'] }" > postcss.config.js
        
    - name: Run builds
      run: npm run build:simple