name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max-old-space-size=4096

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # IMPORTANT: Do not use cache option as it forces npm ci
    
    - name: Use custom npm install action
      uses: ./.github/actions/npm-install-action
      with:
        extra-args: "--prefer-offline"
    
    - name: Verify no lock file exists
      run: |
        if [ -f "package-lock.json" ]; then
          echo "WARNING: package-lock.json still exists - removing it"
          rm -f package-lock.json
        else
          echo "GOOD: No package-lock.json exists"
        fi
    
    - name: Setup PostCSS config
      run: |
        echo "module.exports = { plugins: ['tailwindcss', 'autoprefixer'] }" > postcss.config.js
    
    - name: Build with simplified script
      run: |
        SIMPLE_PDF=true npx next build --no-lint