name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Fix package dependency issues
      run: |
        rm -f package-lock.json
        # Set exact version for is-regexp to avoid version conflicts
        node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json')); pkg.dependencies['is-regexp'] = '2.1.0'; pkg.devDependencies['is-regexp'] = '2.1.0'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
        npm install --no-package-lock
        npm install autoprefixer@9.8.8 postcss@7.0.39 tailwindcss@3.3.0 react-icons@5.5.0 lilconfig@2.1.0 postcss-import@14.1.0 postcss-load-config@3.1.4 postcss-nested@6.0.0 quick-lru@5.1.1 yaml@1.10.2 --save-exact
        
    - name: Setup PostCSS config
      run: |
        echo "module.exports = { plugins: ['tailwindcss', 'autoprefixer'] }" > postcss.config.js
        
    - name: Build project
      run: |
        npm run build:simple