name: Node.js CI - Skip CI

on:
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'Skip build'
        required: false
        default: 'true'

jobs:
  build:
    if: ${{ github.event.inputs.skip_build != 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Fix package dependency issues
      run: |
        rm -f package-lock.json
        # Update package.json to use exact versions for all dependencies
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json'));
          
          // Fix conflicting versions
          pkg.dependencies['is-regexp'] = '2.1.0';
          if (pkg.devDependencies['is-regexp']) pkg.devDependencies['is-regexp'] = '2.1.0';
          pkg.dependencies['react-icons'] = '5.5.0';
          
          // Update package.json
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "
        
        # Install all dependencies with npm install (avoid npm ci)
        npm install --no-package-lock
        
        # Install specific versions of problematic packages
        npm install --save-exact \
          autoprefixer@9.8.8 \
          postcss@7.0.39 \
          tailwindcss@3.3.0 \
          react-icons@5.5.0 \
          lilconfig@2.1.0 \
          postcss-import@14.1.0 \
          postcss-load-config@3.1.4 \
          postcss-nested@6.0.0 \
          quick-lru@5.1.1 \
          yaml@1.10.2
        
    - name: Setup PostCSS config
      run: |
        echo "module.exports = { plugins: ['tailwindcss', 'autoprefixer'] }" > postcss.config.js
        
    - name: Verify no npm ci is used
      run: |
        echo "NOT using npm ci - using npm install instead"
        npm --version
        
    - name: Build project
      run: |
        npm run build:simple